package install

import (
	"context"
	"fmt"
	"io"
	"net"
	"os"
	"runtime"
	"strings"
)

// Packet filtering for the upload listener.
//
// The service already refuses a source outside its allowlist, so this is defence in
// depth rather than the primary control. What it adds is that an unwelcome caller never
// completes a TCP handshake at all: a refusal at the application layer still means the
// port answered, which is enough to probe with.
//
// The rules are deliberately self-sufficient. This host also runs another service that
// owns a pf anchor and rewrites it on its own schedule, and rules that only worked
// because that anchor had already passed the traffic would be a dependency between two
// things that otherwise know nothing about each other.

const (
	pfAnchorName = "orchard"
	pfAnchorPath = "/etc/pf.anchors/orchard"
	pfConfPath   = "/etc/pf.conf"
)

// Firewall prints the rules, or writes and loads them when apply is set.
func Firewall(ctx context.Context, plan Plan, apply bool, w io.Writer) error {
	step := firewallStep{plan: plan}
	if !apply {
		body, err := step.anchor()
		if err != nil {
			return err
		}
		fmt.Fprintf(w, "# would be written to %s\n# and referenced as anchor %q from %s\n\n%s",
			pfAnchorPath, pfAnchorName, pfConfPath, body)
		fmt.Fprintf(w, "\nRe-run with --apply, as root, to install them.\n")
		return nil
	}
	msg, err := step.Apply(ctx)
	if err != nil {
		return err
	}
	fmt.Fprintln(w, msg)
	return nil
}

type firewallStep struct{ plan Plan }

func (firewallStep) Name() string { return "firewall" }

// Check reports on the anchor without touching anything. Applying it is a separate,
// deliberate command: pf here is shared with another service, and reloading it is not
// something an install should do as a side effect.
func (s firewallStep) Check(ctx context.Context) State {
	if s.plan.UploadAddr == "" {
		return OK("upload listener disabled; nothing to restrict")
	}
	if runtime.GOOS != "darwin" {
		return Unverified("no packet-filter integration on %s; the source allowlist still applies", runtime.GOOS)
	}
	if s.plan.UploadAllow == "any" {
		return Unverified("ORCHARD_UPLOAD_ALLOW is \"any\"; nothing to enforce here either")
	}

	want, err := s.anchor()
	if err != nil {
		return Failed("%s", err)
	}

	have, err := os.ReadFile(pfAnchorPath)
	if err != nil {
		return Manual("not installed", s.instructions())
	}
	if string(have) != want {
		return Manual(pfAnchorPath+" differs from this configuration", s.instructions())
	}

	conf, err := os.ReadFile(pfConfPath)
	if err != nil {
		return Unverified("cannot read %s", pfConfPath)
	}
	if !strings.Contains(string(conf), `anchor "`+pfAnchorName+`"`) {
		return Manual("anchor file written but not referenced from "+pfConfPath, s.instructions())
	}

	// Whether pf actually has the rules loaded needs root. Saying "ok" without knowing
	// would be the same lie as reporting green on an unread firewall.
	out, err := run(ctx, "pfctl", "-a", pfAnchorName, "-sr")
	if err != nil {
		return Unverified("anchor wired into %s; reading the live ruleset needs root", pfConfPath)
	}
	if !strings.Contains(out, "block drop") {
		return Failed("the %s anchor is loaded but carries no block rule", pfAnchorName)
	}
	return OK("%s anchor loaded, port %s restricted", pfAnchorName, s.port())
}

func (firewallStep) Fix(context.Context) (string, error) {
	return "", fmt.Errorf("run `sudo orchard firewall --apply`")
}

func (s firewallStep) port() string {
	_, port, err := net.SplitHostPort(s.plan.UploadAddr)
	if err != nil {
		return ""
	}
	return port
}

func (s firewallStep) instructions() string {
	return "The source allowlist already refuses these callers; this stops the port\n" +
		"answering them at all. Applying it rewrites pf, which is shared with anything\n" +
		"else on this host that uses it, so it is a separate deliberate step:\n\n" +
		"  sudo orchard firewall --apply\n\n" +
		"`sudo orchard firewall` on its own prints the rules without installing them."
}

// anchor renders the ruleset.
//
// Order matters: pf takes the first `quick` match, so every pass has to precede the
// block. The rules name no other service and no interface, so a bridge that renumbers
// or an anchor that is rewritten elsewhere cannot change what this does.
func (s firewallStep) anchor() (string, error) {
	port := s.port()
	if port == "" {
		return "", fmt.Errorf("cannot read a port from ORCHARD_UPLOAD_ADDR %q", s.plan.UploadAddr)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by orchard. Loaded as the %q anchor from %s.\n#\n", pfAnchorName, pfConfPath)
	b.WriteString("# The upload listener is plain HTTP and its bearer token crosses the wire in\n")
	b.WriteString("# cleartext. It exists for guests on this host, which reach it through their own\n")
	b.WriteString("# default gateway. Nothing off this machine should be able to open a connection\n")
	b.WriteString("# to it at all.\n#\n")
	b.WriteString("# The service refuses such callers itself; this is the layer that stops them\n")
	b.WriteString("# completing a handshake first. Keep both: this one is absent whenever pf is\n")
	b.WriteString("# disabled, and that is not a thing the service can detect.\n\n")

	fmt.Fprintf(&b, "pass in quick on lo0 proto tcp to any port %s\n", port)
	for _, cidr := range strings.Split(s.plan.UploadAllow, ",") {
		cidr = strings.TrimSpace(cidr)
		if cidr == "" || strings.HasPrefix(cidr, "127.") || cidr == "::1" {
			continue // loopback is covered by the lo0 rule above
		}
		fmt.Fprintf(&b, "pass in quick proto tcp from %s to any port %s\n", cidr, port)
	}
	fmt.Fprintf(&b, "block drop in quick proto tcp to any port %s\n", port)
	return b.String(), nil
}

// Apply writes the anchor and loads it. It is called only by `orchard firewall --apply`.
func (s firewallStep) Apply(ctx context.Context) (string, error) {
	if runtime.GOOS != "darwin" {
		return "", fmt.Errorf("packet-filter integration is macOS only; on %s use the source allowlist, or nftables", runtime.GOOS)
	}
	if err := requireRoot("writing " + pfAnchorPath); err != nil {
		return "", err
	}
	body, err := s.anchor()
	if err != nil {
		return "", err
	}

	if err := os.MkdirAll("/etc/pf.anchors", 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(pfAnchorPath, []byte(body), 0o644); err != nil {
		return "", err
	}

	// Reference it from pf.conf if it is not already there. Another service on this
	// host owns its own anchor in the same file; only orchard's own lines are touched,
	// and the original is kept.
	conf, err := os.ReadFile(pfConfPath)
	if err != nil {
		return "", err
	}
	added := false
	if !strings.Contains(string(conf), `anchor "`+pfAnchorName+`"`) {
		if err := os.WriteFile(pfConfPath+".orchard.bak", conf, 0o644); err != nil {
			return "", err
		}
		updated := strings.TrimRight(string(conf), "\n") + fmt.Sprintf(
			"\n\n# orchard upload listener\nanchor %q\nload anchor %q from %q\n",
			pfAnchorName, pfAnchorName, pfAnchorPath)
		if err := os.WriteFile(pfConfPath, []byte(updated), 0o644); err != nil {
			return "", err
		}
		added = true
	}

	// Parse before loading, so a bad ruleset is a message rather than a firewall that
	// stopped filtering.
	if out, err := run(ctx, "pfctl", "-n", "-f", pfConfPath); err != nil {
		return "", fmt.Errorf("%s does not parse, nothing loaded: %s", pfConfPath, out)
	}
	if out, err := run(ctx, "pfctl", "-f", pfConfPath); err != nil {
		return "", fmt.Errorf("loading %s failed: %s", pfConfPath, out)
	}
	// pf is off by default on macOS and the rules do nothing until it is enabled.
	// -e on an already-enabled pf reports an error that is not one.
	if out, err := run(ctx, "pfctl", "-e"); err != nil && !strings.Contains(out, "already enabled") {
		return "", fmt.Errorf("enabling pf failed: %s", out)
	}

	if added {
		return fmt.Sprintf("wrote %s and referenced it from %s (original saved as %s.orchard.bak)",
			pfAnchorPath, pfConfPath, pfConfPath), nil
	}
	return fmt.Sprintf("updated %s and reloaded pf", pfAnchorPath), nil
}
